<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LP0041710" failures="1" tests="8" name="User Menu Drop Down" time="84.97" errors="0" timestamp="2025-02-10T09:50:11 CST">
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="inCorrectCredentialErrorMsg" time="3.418"/>
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="inCorrectCredentialErrorMsg" time="7.812"/>
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="inCorrectCredentialErrorMsg" time="5.447"/>
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="loginErrorMsg" time="2.145">
    <skipped/>
  </testcase> <!-- loginErrorMsg -->
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="loginErrorMsg" time="2.522">
    <failure type="java.lang.AssertionError" message="expected [fPlease enter your password.] but found [Please enter your password.]">
      <![CDATA[java.lang.AssertionError: expected [fPlease enter your password.] but found [Please enter your password.]
at com.salesForce.Test.SDLCLoginTest.loginErrorMsg(SDLCLoginTest.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorMsg -->
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="loginToSalesForce" time="5.353"/>
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="checkRememberMe" time="10.972"/>
  <testcase classname="com.salesForce.Test.SDLCLoginTest" name="forgotPsw" time="2.029"/>
</testsuite> <!-- User Menu Drop Down -->
